apiVersion: "machineconfigurations.openshift.io/v1"
kind: "ControllerConfig"
spec:
  clusterDNSIP: "10.3.0.10"
  cloudProviderConfig: |
    testing
    multi-line cloud config
    [test]
      option = dummy
  etcdDiscoveryDomain: "my-test-cluster.example.org"
  etcdInitialCount: 3
  platform: "ovirt"
  etcdCAData: OHVtbXkgZXRjZC1jYQo=
  rootCAData: OHVtbXkgcm9vdC1jYQo=
  pullSecret:
    data: OHVtbXkgZXRjZC1jYQo=
  images:
    etcd: image/etcd:1
    setupEtcdEnv: image/setupEtcdEnv:1
    infraImage: image/infraImage:1
    kubeClientAgentImage: image/kubeClientAgentImage:1
