name: machine-config-daemon-firstboot.service
enabled: true
contents: |
  [Unit]
  Description=Machine Config Daemon Firstboot
  # Make sure it runs only on OSTree booted system
  ConditionPathExists=/run/ostree-booted
  # Removal of this file signals firstboot completion
  ConditionPathExists=/etc/ignition-machine-config-encapsulated.json
  # We only want to run on 4.3 clusters and above; this came from
  # https://github.com/coreos/coreos-assembler/pull/768
  ConditionPathExists=/sysroot/.coreos-aleph-version.json
  After=machine-config-daemon-pull.service
  Before=crio.service crio-wipe.service
  Before=kubelet.service
  Before=zincati.service

  [Service]
  # Need oneshot to delay kubelet
  Type=oneshot
  # Create /usr/local/bin symbolic link unless it exists
  ExecStart=-/usr/bin/ln --symbolic /usr/libexec/bin/machine-config-daemon /usr/local/bin/machine-config-daemon
  ExecStart=/usr/local/bin/machine-config-daemon firstboot-complete-machineconfig

  [Install]
  WantedBy=multi-user.target
  RequiredBy=crio.service kubelet.service
