name: machine-config-daemon-firstboot.service
enabled: true
contents: |
  [Unit]
  Description=Machine Config Daemon Firstboot
  # Make sure it runs only on OSTree booted system
  ConditionPathExists=/run/ostree-booted
  # Removal of this file signals firstboot completion
  ConditionPathExists=/etc/ignition-machine-config-encapsulated.json
  After=machine-config-daemon-pull.service
  Before=crio.service crio-wipe.service
  Before=kubelet.service

  [Service]
  Type=oneshot
  RemainAfterExit=yes
  ExecStart=/usr/bin/rm -rf /etc/yum.repos.d/
  ExecStart=/run/bin/machine-config-daemon firstboot-complete-machineconfig

  {{if .Proxy -}}
  {{if .Proxy.HTTPProxy -}}
  Environment=HTTP_PROXY={{.Proxy.HTTPProxy}}
  {{end -}}
  {{if .Proxy.HTTPSProxy -}}
  Environment=HTTPS_PROXY={{.Proxy.HTTPSProxy}}
  {{end -}}
  {{if .Proxy.NoProxy -}}
  Environment=NO_PROXY={{.Proxy.NoProxy}}
  {{end -}}
  {{end -}}

  [Install]
  WantedBy=multi-user.target
  RequiredBy=crio.service kubelet.service
